version: '2'
services: 
  mysql:
    image: mysql:5.7.4
    ports: 
     - "3307:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USERNAME=root
  redis:
     image: redis
     ports: 
      - "6381:6379"
  zkc123:
    image: younger123:latest
    ports: 
    - "8888:8080"